#!/bin/bash

##
# Wrapper for running fig while having only Docker
docker-compose() {
    local project
    local -a args=( "$@" )
    local i
    for i in "${!args[@]}"; do
        case "${args[i]}" in
            -p|--project-name)
                project="${args[i+1]}"
                unset args[i] args[i+1]
                break
                ;;
        esac
    done
    project="${project:-$PWD}"      # Default to PWD
    project="${project##*/}"        # basename
    project="${project,,}"          # lowercase
    project="${project//[^a-z0-9]}" # keep only alnum
    docker run --env "OUTER_PWD=$PWD" \
               --interactive \
               --privileged \
               --rm \
               --tty \
               --volume "${PWD}:${PWD}" \
               --volume /var/run/docker.sock:/var/run/docker.sock \
               --workdir "$PWD" \
               kojiromike/docker-compose-wrapper \
               -p "$project" \
               "${args[@]}"
}
